project:
  name: 'docs'
  tag: 'docs'
  url: 'https://docs.mongodb.com'
  branched: false
assets:
  - branch: nav
    path: build/nav
    repository: http://github.com/mongodb/docs-assets.git
version:
   release: 'current'
   branch: 'current'
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
...
